### ISSUE TITLE
"Index Out of Range" error on all links tried

### ISSUE THREAD

**Issue by kolt54321** [expenses/GAPDownloader#13]
Hi - when I try the tool recently (zoom 7), I get the following error:

Downloading image meta-information...

Traceback (most recent call last):
  File "tile_fetch.py", line 178, in <module>
    main()
  File "tile_fetch.py", line 159, in main
    image_info = ImageInfo(url)
  File "tile_fetch.py", line 61, in __init__
    self.token = re.findall(token_regex, page_source)[0]
IndexError: list index out of range

Thanks!

**Comment by lovasoa** [comment]
The way token appear in google arts pages changed recently. See https://github.com/lovasoa/dezoomify/issues/330

dezoomify and dezoomify-rs were updated, but not gapdecoder

@kolt54321 Would you be interested in making a pull request ?

**Comment by lovasoa** [comment]
Here is the change in dezoomify, that should be replicated: https://github.com/lovasoa/dezoomify/commit/7dd2dd658e806aac7b9362da4e404a1bf3c4fb83

**Comment by kolt54321** [comment]
@lovasoa I took a look, but my programming knowledge is simply lacking I'm afraid, I'm sorry I'm not sure how to implement the new format...

**Comment by lovasoa** [comment]
It should be fixed, you can try the latest version

**Comment by kolt54321** [comment]
Thanks - but I think it now only recognizes zoom 2. Trying on these two scans it doesn't seem to recognize higher depth options.

https://artsandculture.google.com/asset/iced/qgG0-NEOLT3UMg
https://artsandculture.google.com/asset/a-painted-picture-of-the-universe-roy-de-maistre/SwGpUlgTvGW_-g

**Comment by lovasoa** [comment]
These two images do not have a zoom level higher than 2.

**Comment by lovasoa** [comment]
Both images have three levels (0, 1 and 2), all three are recognized by gapdecoder. No bug here.

**Comment by lovasoa** [comment]
Oh, I see what you mean. We access the list of zoom levels from the `og:image` url, and get a version with just 3 levels:
https://lh5.ggpht.com/g6wFpTpwYRcKWug2uBS4G6JmOJXYCjcWUz7DLGVdiBW38V5yvsimWLqagu85=g

The page itself gets it from:
https://lh5.ggpht.com/Q9a7W5fE_7ZAnvA3L06jSehH-gq2RVeDBwMDyCIhkJU8zKdET--jzpSXDMyYMg=g

And it gets 7 levels

**Comment by kolt54321** [comment]
Yep! Sorry for the lack of clarification.

Edit: I believe dezoomify-rs recognizes all 7 levels.

**Comment by lovasoa** [comment]
I created a new issue to track this new problem

**Comment by kolt54321** [comment]
> I created a new issue to track this new problem

Thanks! I believe dezoomify-rs recognizes all 7 levels, but am not sure what the difference is between the two's underlying mechanics..
