### ISSUE TITLE
No Module Named: 'aiohttp'

### ISSUE THREAD

**Issue by jaaschutz** [expenses/GAPDownloader#21]
Hello!! Thanks so much for creating this program. Running into a new error (this worked a few weeks ago). Looking to see if there is a new replacement for aiohttp.

PS C:\Users\Jozef Schutzman\Documents\gapdecoder-master\gapdecoder-master>  python3 tile_fetch.py "https://artsandculture.google.com/asset/flag-of-east-timor-dom%C3%ADnio-p%C3%BAblico/WAHnaoBLfc9U6g"
Traceback (most recent call last):
  File "tile_fetch.py", line 15, in <module>
    import aiohttp
ModuleNotFoundError: No module named 'aiohttp'

**Comment by jaaschutz** [comment]
Sorry just needed to update dependencies

**Comment by lovasoa** [comment]
You can also use dezoomify-rs, which should be faster and for which you won't have to manually handle dependencies

**Comment by jaaschutz** [comment]
Hey @lovasoa , I tried rs, but I was getting the following error

Enter an URL or a path to a tiles.yaml file:
https://artsandculture.google.com/asset/light-in-the-dark/ZQFouDGMVmsI2w
Found the following zoom levels:
0. Light in the dark - Domenico Pesenti (  374 x   271 pixels,     1 tiles)
1. Light in the dark - Domenico Pesenti (  748 x   542 pixels,     4 tiles)
2. Light in the dark - Domenico Pesenti ( 1497 x  1085 pixels,     9 tiles)
3. Light in the dark - Domenico Pesenti ( 2995 x  2171 pixels,    30 tiles)
4. Light in the dark - Domenico Pesenti ( 5991 x  4343 pixels,   108 tiles)
5. Light in the dark - Domenico Pesenti (11983 x  8687 pixels,   408 tiles)
6. Light in the dark - Domenico Pesenti (23967 x 17375 pixels,  1598 tiles)
7. Light in the dark - Domenico Pesenti (47934 x 34750 pixels,  6392 tiles)
Which level do you want to download?
7
ERROR Input/Output error: Access is denied. (os error 5)
