### ISSUE TITLE
Zoom 7 hangs, or has greatly increased download time vs Zoom 6

### ISSUE THREAD

**Issue by kolt54321** [expenses/GAPDownloader#3]
Hey! So I'm really enjoying the tool, even though I'm not familiar with the methods used to obtain the images.

One thing I noticed is that Zoom 7 (the highest I've tried so far) seems to hang at around ~40%, and at other times takes considerably longer than Zoom 6. Generally speaking the scans being pointed at had 4x the tiles in Zoom 7 vs 6. However, while Zoom 6 takes around ~3 minutes, Zoom 7 takes 30 min or so before hitting that arbitrary point where it stops.

If this is part and parcel of the way the script works, that's great - Zoom 7 isn't even remotely available in the other GA&C tools. I just thought I'd reach out and ask if it's something expected.

The scans in mention are part of the [Gigapixel collection](https://artsandculture.google.com/usergallery/art-project-gigapixels/DAJiOwFKTTbQLQ). I beilieve [this](https://artsandculture.google.com/asset/proceeding-lion-detail-from-the-processional-way-of-babylon/QAFcGuAYEoi2sA) was a problem file.

Edit: So I'm seeing most files fail on zoom 7, downloads a number of tiles and then starts. It is possible to pick up where it left off by re-running the command, but that only goes so far if it's a glitch that it gets stuck. Unfortunately there seems to be times where all restarting does is downloads a few more tiles.

**Comment by lovasoa** [comment]
Hello, and thank you for using this tool !
  There may be a way to investigate the issue, but you will have to give more details:

 - What is the exact error message when it hangs ? Could you copy & paste the whole output ?
 - What version of python are you using (you can paste the output of python -VV) ? Do you have a 32-bit or a 64-bit version of python ?
 - How much memory do you have on your computer ? An approximation for the number of bytes of memory you should have available to create an image is `4*width*height`.

**Comment by kolt54321** [comment]
Hey! Thanks for the response. 

It hasn't happened to me in a bit, but earlier, it would hang, without actually breaking. I.e. not download any more tiles.

I'm at work now, but I believe I used python 3.7, 64-bit. 32-bit will result in "out of memory" errors. i have 16gb of RAM, DDR3 however. I can confirm Zoom 8 works now.

Very interesting on the RAM approximation! looks like most of the gigapixel scans on zoom 8 hover at around 16-20gb RAM if the math is correct.. I haven't faced this issue in a while though, for some reason it disappeared.

I have some other info on final output (right now the code saves as .jpg, which is problematic given we want the best quality available, and it's a lossy format), using numpy/tifffile to save the output as BigTIFF - .png works, but the colors are not optimal, and .TIFF works, but has a 4gb size limit (most of the --zoom 8's are larger than that).  I can try a fork (never used github before, so not sure if it's the right word) or you can PM me @ kolt54321@gmail if you want it quicker in the official distro. 

This may be placebo, but I think downloading the tiles/output as .png or .TIFF speeds up the process. Though it's possible it's just my internet getting better/worse, or maybe compression of all the thousands of tiles into .jpg adds to the processing time.

**Comment by lovasoa** [comment]
The code uses the file extension to guess the format in which to save. So, `--outfile my_image.png`
 would output a losslessly compressed PNG file. Note however that the tiles themselves are served by google only in jpeg, so you should not expect any visible quality difference.

Currently, the connection to google is closed after each downloaded tile, and reopened for the next. The thing that could help with download speed would be to keep a pool of connections opened all the time, and making requests through them. Error handling could also be improved. Pull requests are welcome :)

**Comment by JohnDoee** [comment]
When browsing the site with a webbrowser, it requests multiple tiles at once so throwing in a threadpool would probably speed things up without doing anything Google does not expect to happen already.

Using a requests.Session() seems to improve keep-alive and then maybe 4 download threads ? What do you think about that @lovasoa ?

**Comment by kolt54321** [comment]
@lovasoa I noticed the tiles from Google are jpeg, good point! I'm just concerned about a double compression when we compile and save the entire image (similar to how converting MP3 to MP3 results in data degradation). I'm poorly versed in how the compression works on saving, but do you think this might be an issue?

I created a new branch with tifffile logic, but it's a stretch at best. Converting the entire image in memory to a numpy array so tifffile can save it as bigtiff works, but is probably not optimal.

**Comment by lovasoa** [comment]
@kolt54321 I am not an expert, but I don't think JPEG re-compression has any noticeable effect on quality. Why don't you just try, before starting to implement anything ?

@JohnDoee I was thinking of using the simple standard library's `http.client`. But if you think there are interesting features in requests that would not be trivial to reproduce, then we could consider adding a new dependency. Also, I noticed we have a hardcoded `lh3.googleusercontent.com` in the HTTP url, whereas the website itself seems to use different subdomains for different images (from`lh3` to `lh6`).

**Comment by kolt54321** [comment]
@lovasoa I'm just a poor kid with a 720p screen. You're probably right that there's no noticeable effect (jpeg compression keeps the necessary detail to the eye), and there wouldn't be any way for me to tell either way. Just thought I'd bring it up :)

**Comment by JohnDoee** [comment]
@lovasoa Google got two different CDNs, the one you named and `ggpht.com`. Only the last one got round-robin functionality at least according to the Javascript logic. Not sure how many images actually use this though, my test image did not at least.

**Comment by lovasoa** [comment]
@kolt54321 I just made a small experiment. I measured the [PSNR](https://en.wikipedia.org/wiki/Peak_signal-to-noise_ratio) of PNG(JPEG(image)) versus JPEG(JPEG(image). I used ImageMagick for both compression and quality measurements. I used q=90 for jpeg compression. Here are the results

### PNG(JPEG(image))
Image: lenna2.png
  Channel distortion: PSNR
    red: 37.0566
    green: 38.1482
    blue: 34.1907
    all: 36.1313

### JPEG(JPEG(image))
Image: lenna2.jpg
  Channel distortion: PSNR
    red: 36.9668
    green: 38.0948
    blue: 34.139
    all: 36.0689

## Conclusion
Save your images as jpeg. They will be much smaller, and the difference in the signal to noise ratio will be under 0.1dB, way smaller than anything you can see.

**Comment by kolt54321** [comment]
@lovasoa Awesome! Thanks for taking the time to explain, that's very informative.

Just to clarify, PNG vs TIFF shouldn't matter from the color aspect as both are RGB and 8-bit depth here, right?

**Comment by lovasoa** [comment]
The original tiles are in 8 bit RGB, so you cannot hope to get anything more than that in the output.

**Comment by kolt54321** [comment]
> The original tiles are in 8 bit RGB, so you cannot hope to get anything more than that in the output.

Many thanks! It's 8gb per channel, right? Just looking to understand. No alpha parameter hosted on their end either, right (for RGB**A**, for instance)?

I think the default compression in PIL is 75 (if I understand correctly, on the scale from 1-95), but it's probably similar results. Good to know.

**Comment by lovasoa** [comment]
I implemented an asynchronous tile fetcher (that downloads several tiles at the same time, and retries downloads up to 5 times when they fail). I am seeing a ~30% speedup (measured on the whole process).

I published the changes to https://github.com/expenses/gapdecoder/tree/async_fetch.
Can you try it ?
