### ISSUE TITLE
Move to organisation repo?

### ISSUE THREAD

**Issue by expenses** [expenses/GAPDownloader#6]
Seeing as I'm not active on this project, perhaps it would be better to move it to an organisation repo or something?

**Comment by lovasoa** [comment]
Good idea !

**Comment by lovasoa** [comment]
@expenses, can you create the organization and move the repo?

**Comment by lovasoa** [comment]
@expenses Maybe you could transfer ownership to me ?

**Comment by lovasoa** [comment]
@expenses : I see you moved the repo to an organization. Can you add me to the gap-decoder organization ?

**Comment by expenses** [comment]
shit, sorry, I thought I did.

**Comment by lovasoa** [comment]
Thank you !
